import { strict as assert } from 'node:assert';
import { readFileSync,writeFileSync } from 'node:fs';
import { PDFDocument } from 'pdf-lib';
import { readInvoice,renderInvoice } from './render.mjs';
const party=(name,doc)=>`<cac:Party><cac:PartyIdentification><cbc:ID schemeID="6">${doc}</cbc:ID></cac:PartyIdentification><cac:PartyLegalEntity><cbc:RegistrationName>${name}</cbc:RegistrationName></cac:PartyLegalEntity></cac:Party>`;
const line=`<cac:InvoiceLine><cbc:ID>1</cbc:ID><cbc:InvoicedQuantity unitCode="NIU">10</cbc:InvoicedQuantity><cbc:LineExtensionAmount>100.00</cbc:LineExtensionAmount><cac:Item><cbc:Description>Papel higiénico MEGA XL &amp; presentación familiar</cbc:Description></cac:Item><cac:Price><cbc:PriceAmount>10.00</cbc:PriceAmount></cac:Price><cac:PricingReference><cac:AlternativeConditionPrice><cbc:PriceAmount>11.80</cbc:PriceAmount><cbc:PriceTypeCode>01</cbc:PriceTypeCode></cac:AlternativeConditionPrice></cac:PricingReference></cac:InvoiceLine>`;
const xml=`<?xml version="1.0"?><Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2" xmlns:cbc="cbc" xmlns:cac="cac" xmlns:ext="ext" xmlns:ds="ds"><cbc:ID>F001-123</cbc:ID><cbc:IssueDate>2026-10-02</cbc:IssueDate><cbc:InvoiceTypeCode>01</cbc:InvoiceTypeCode><cbc:DocumentCurrencyCode>PEN</cbc:DocumentCurrencyCode><cac:AccountingSupplierParty>${party('EMISOR DE PRUEBA','20000000001')}</cac:AccountingSupplierParty><cac:AccountingCustomerParty>${party('CLIENTE DE PRUEBA','20000000002')}</cac:AccountingCustomerParty><cac:TaxTotal><cac:TaxSubtotal><cbc:TaxableAmount>100.00</cbc:TaxableAmount><cbc:TaxAmount>18.00</cbc:TaxAmount><cac:TaxCategory><cac:TaxScheme><cbc:ID>1000</cbc:ID><cbc:Name>IGV</cbc:Name></cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal></cac:TaxTotal><cac:LegalMonetaryTotal><cbc:PayableAmount>118.00</cbc:PayableAmount></cac:LegalMonetaryTotal><cac:PaymentTerms><cbc:ID>FormaPago</cbc:ID><cbc:PaymentMeansID>Contado</cbc:PaymentMeansID></cac:PaymentTerms><ext:UBLExtensions><ext:UBLExtension><ext:ExtensionContent><ds:Signature><ds:SignedInfo><ds:Reference><ds:DigestValue>RESUMEN-DE-PRUEBA</ds:DigestValue></ds:Reference></ds:SignedInfo></ds:Signature></ext:ExtensionContent></ext:UBLExtension></ext:UBLExtensions>${line}</Invoice>`;
const d=readInvoice(xml);assert.equal(d.total,'118.00');assert.equal(d.igv,'18.00');assert.equal(d.lines[0].quantity,'10');assert.equal(d.lines[0].unitValue,'10.00');assert.equal(d.lines[0].unitPrice,'11.80');assert.equal(d.customer,'CLIENTE DE PRUEBA');assert.equal(d.qr,'20000000001|01|F001|123|18.00|118.00|2026-10-02|6|20000000002|RESUMEN-DE-PRUEBA');assert.match(d.lines[0].description,/ & /);
assert.throws(()=>readInvoice(xml.replace('>01<','>03<')));assert.throws(()=>readInvoice('<!DOCTYPE Invoice>'+xml));
const result=await renderInvoice(xml,'ACEPTADO_BETA');writeFileSync('/workspace/scratch/2434516b2eaf/tmp/pdfs/factura-generada.pdf',result.bytes);
const pdf=await PDFDocument.load(result.bytes);assert.equal(pdf.getPageCount(),1);
const long=await renderInvoice(xml.replace(line,line.repeat(120)),'ACEPTADO_BETA');const pages=(await PDFDocument.load(long.bytes)).getPageCount();assert.ok(pages>2);
console.log('OK: XML values, QR payload, malformed XML, unsupported types, PDF and pagination ('+pages+' pages).');

const withDiscount=xml.replace('<cac:LegalMonetaryTotal>','<cac:AllowanceCharge><cbc:ChargeIndicator>false</cbc:ChargeIndicator><cbc:Amount>10.00</cbc:Amount></cac:AllowanceCharge><cac:LegalMonetaryTotal><cbc:AllowanceTotalAmount>15.00</cbc:AllowanceTotalAmount>').replace('<cac:InvoiceLine>','<cac:InvoiceLine><cac:AllowanceCharge><cbc:ChargeIndicator>false</cbc:ChargeIndicator><cbc:Amount>5.00</cbc:Amount></cac:AllowanceCharge>');
const discounted=readInvoice(withDiscount);assert.equal(discounted.discount,'15.00');assert.equal(discounted.globalDiscount,'10.00');assert.equal(discounted.itemDiscount,'5.00');assert.equal(discounted.lines[0].discount,'5.00');assert.equal(d.discount,'0.00');console.log('OK: item/global discounts and XML total without double-counting.');
