export const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const round=v=>Math.round((Number(v)+Number.EPSILON)*100)/100;
const n=v=>Number(v??0).toFixed(2);
export const limaDate=v=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v));
const amount=(tag,v)=>`<${tag} currencyID="PEN">${n(v)}</${tag}>`;
const ns='xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2"';
const extension='<ext:UBLExtensions><ext:UBLExtension><ext:ExtensionContent/></ext:UBLExtension></ext:UBLExtensions>';
const signature=cfg=>`<cac:Signature><cbc:ID>${esc(cfg.ruc)}</cbc:ID><cac:SignatoryParty><cac:PartyIdentification><cbc:ID>${esc(cfg.ruc)}</cbc:ID></cac:PartyIdentification><cac:PartyName><cbc:Name>${esc(cfg.nombre_empresa)}</cbc:Name></cac:PartyName></cac:SignatoryParty><cac:DigitalSignatureAttachment><cac:ExternalReference><cbc:URI>#SignatureSP</cbc:URI></cac:ExternalReference></cac:DigitalSignatureAttachment></cac:Signature>`;
const tax=(base,igv,line=false)=>`<cac:TaxTotal>${amount('cbc:TaxAmount',igv)}<cac:TaxSubtotal>${amount('cbc:TaxableAmount',base)}${amount('cbc:TaxAmount',igv)}<cac:TaxCategory>${line?'<cbc:Percent>18.00</cbc:Percent><cbc:TaxExemptionReasonCode>10</cbc:TaxExemptionReasonCode>':''}<cac:TaxScheme><cbc:ID>1000</cbc:ID><cbc:Name>IGV</cbc:Name><cbc:TaxTypeCode>VAT</cbc:TaxTypeCode></cac:TaxScheme></cac:TaxCategory></cac:TaxSubtotal></cac:TaxTotal>`;
function party(cfg,d,address){const doc=String(d.cliente_documento||'');const scheme=doc.length===11?'6':doc.length===8?'1':'0';return `<cac:AccountingSupplierParty><cac:Party><cac:PartyIdentification><cbc:ID schemeID="6">${esc(cfg.ruc)}</cbc:ID></cac:PartyIdentification><cac:PartyLegalEntity><cbc:RegistrationName>${esc(cfg.nombre_empresa)}</cbc:RegistrationName><cac:RegistrationAddress><cbc:AddressTypeCode>0000</cbc:AddressTypeCode><cac:AddressLine><cbc:Line>${esc(cfg.direccion)}</cbc:Line></cac:AddressLine><cac:Country><cbc:IdentificationCode>PE</cbc:IdentificationCode></cac:Country></cac:RegistrationAddress></cac:PartyLegalEntity></cac:Party></cac:AccountingSupplierParty><cac:AccountingCustomerParty><cac:Party><cac:PartyIdentification><cbc:ID schemeID="${scheme}">${esc(doc||'-')}</cbc:ID></cac:PartyIdentification><cac:PartyLegalEntity><cbc:RegistrationName>${esc(d.cliente_nombre)}</cbc:RegistrationName>${address?`<cac:RegistrationAddress><cac:AddressLine><cbc:Line>${esc(address)}</cbc:Line></cac:AddressLine></cac:RegistrationAddress>`:''}</cac:PartyLegalEntity></cac:Party></cac:AccountingCustomerParty>`;}
export function invoiceXml(d,items,cfg,address='',ref=null){
 const credit=d.tipo==='nota_credito',type=credit?'07':d.tipo==='factura'?'01':'03',root=credit?'CreditNote':'Invoice';
 if(!['factura','boleta','nota_credito'].includes(d.tipo)||!/^\d{11}$/.test(cfg.ruc)||!cfg.direccion)throw Error('Datos fiscales del emisor incompletos');
 if(!items.length||items.some(x=>!(Number(x.cantidad)>0)||!(Number(x.precio_unitario)>0)||Math.abs(round(x.cantidad*x.precio_unitario)-Number(x.subtotal))>.01))throw Error('Ítems inconsistentes');
 if((type==='01'||ref?.tipo==='factura')&&!/^\d{11}$/.test(d.cliente_documento||''))throw Error('La factura requiere RUC del comprador');
 if(credit&&(!ref||d.motivo_codigo!=='01'))throw Error('Por ahora se admite anulación total de una operación aceptada');
 const bases=items.map(x=>round(Number(x.subtotal)/1.18));const grossBase=round(items.reduce((s,x)=>s+Number(x.subtotal),0)/1.18);
 bases[bases.length-1]=round(bases.at(-1)+grossBase-round(bases.reduce((a,b)=>a+b,0)));
 const discount=round(grossBase-Number(d.valor_venta));
 if(discount<0||Math.abs(round(Number(d.total)/1.18)-Number(d.valor_venta))>.02||Math.abs(round(Number(d.valor_venta)+Number(d.igv))-Number(d.total))>.01||Math.abs(round(items.reduce((s,x)=>s+Number(x.subtotal),0)-Number(d.descuento))-Number(d.total))>.02)throw Error('Los totales no coinciden con la venta');
 const global=discount>0?`<cac:AllowanceCharge><cbc:ChargeIndicator>false</cbc:ChargeIndicator><cbc:AllowanceChargeReasonCode>02</cbc:AllowanceChargeReasonCode><cbc:MultiplierFactorNumeric>${(discount/grossBase).toFixed(5)}</cbc:MultiplierFactorNumeric>${amount('cbc:Amount',discount)}${amount('cbc:BaseAmount',grossBase)}</cac:AllowanceCharge>`:'';
 const lines=items.map((x,i)=>`<cac:${credit?'CreditNoteLine':'InvoiceLine'}><cbc:ID>${i+1}</cbc:ID><cbc:${credit?'CreditedQuantity':'InvoicedQuantity'} unitCode="NIU">${x.cantidad}</cbc:${credit?'CreditedQuantity':'InvoicedQuantity'}>${amount('cbc:LineExtensionAmount',bases[i])}<cac:PricingReference><cac:AlternativeConditionPrice>${amount('cbc:PriceAmount',x.precio_unitario)}<cbc:PriceTypeCode>01</cbc:PriceTypeCode></cac:AlternativeConditionPrice></cac:PricingReference>${tax(bases[i],round(Number(x.subtotal)-bases[i]),true)}<cac:Item><cbc:Description>${esc(x.producto_nombre)}</cbc:Description></cac:Item><cac:Price><cbc:PriceAmount currencyID="PEN">${(Number(x.precio_unitario)/1.18).toFixed(10)}</cbc:PriceAmount></cac:Price></cac:${credit?'CreditNoteLine':'InvoiceLine'}>`).join('');
 const reference=credit?`<cac:DiscrepancyResponse><cbc:ReferenceID>${esc(ref.serie)}-${ref.correlativo}</cbc:ReferenceID><cbc:ResponseCode>01</cbc:ResponseCode><cbc:Description>${esc(d.motivo_descripcion)}</cbc:Description></cac:DiscrepancyResponse><cac:BillingReference><cac:InvoiceDocumentReference><cbc:ID>${esc(ref.serie)}-${ref.correlativo}</cbc:ID><cbc:DocumentTypeCode>${ref.tipo==='factura'?'01':'03'}</cbc:DocumentTypeCode></cac:InvoiceDocumentReference></cac:BillingReference>`:'';
 return `<?xml version="1.0" encoding="UTF-8"?><${root} xmlns="urn:oasis:names:specification:ubl:schema:xsd:${root}-2" ${ns}>${extension}<cbc:UBLVersionID>2.1</cbc:UBLVersionID><cbc:CustomizationID>2.0</cbc:CustomizationID><cbc:ID>${esc(d.serie)}-${d.correlativo}</cbc:ID><cbc:IssueDate>${limaDate(d.created_at)}</cbc:IssueDate>${credit?'':`<cbc:InvoiceTypeCode listID="0101">${type}</cbc:InvoiceTypeCode>`}<cbc:DocumentCurrencyCode>PEN</cbc:DocumentCurrencyCode>${reference}${signature(cfg)}${party(cfg,d,address)}${credit?'':'<cac:PaymentTerms><cbc:ID>FormaPago</cbc:ID><cbc:PaymentMeansID>Contado</cbc:PaymentMeansID></cac:PaymentTerms>'}${global}${tax(d.valor_venta,d.igv)}<cac:LegalMonetaryTotal>${amount('cbc:LineExtensionAmount',grossBase)}${amount('cbc:TaxInclusiveAmount',d.total)}${discount?amount('cbc:AllowanceTotalAmount',discount):''}${amount('cbc:PayableAmount',d.total)}</cac:LegalMonetaryTotal>${lines}</${root}>`;
}
export function summaryXml(d,cfg,id,date,ref=null){
 const doc=d.cliente_documento||'-',scheme=doc.length===11?'6':doc.length===8?'1':'0';
 return `<?xml version="1.0" encoding="UTF-8"?><SummaryDocuments xmlns="urn:sunat:names:specification:ubl:peru:schema:xsd:SummaryDocuments-1" ${ns} xmlns:sac="urn:sunat:names:specification:ubl:peru:schema:xsd:SunatAggregateComponents-1">${extension}<cbc:UBLVersionID>2.0</cbc:UBLVersionID><cbc:CustomizationID>1.1</cbc:CustomizationID><cbc:ID>${id}</cbc:ID><cbc:ReferenceDate>${limaDate(d.created_at)}</cbc:ReferenceDate><cbc:IssueDate>${date}</cbc:IssueDate>${signature(cfg)}<cac:AccountingSupplierParty><cbc:CustomerAssignedAccountID>${cfg.ruc}</cbc:CustomerAssignedAccountID><cbc:AdditionalAccountID>6</cbc:AdditionalAccountID><cac:Party><cac:PartyLegalEntity><cbc:RegistrationName>${esc(cfg.nombre_empresa)}</cbc:RegistrationName></cac:PartyLegalEntity></cac:Party></cac:AccountingSupplierParty><sac:SummaryDocumentsLine><cbc:LineID>1</cbc:LineID><cbc:DocumentTypeCode>${d.tipo==='nota_credito'?'07':'03'}</cbc:DocumentTypeCode><cbc:ID>${d.serie}-${d.correlativo}</cbc:ID><cac:AccountingCustomerParty><cbc:CustomerAssignedAccountID>${esc(doc)}</cbc:CustomerAssignedAccountID><cbc:AdditionalAccountID>${scheme}</cbc:AdditionalAccountID></cac:AccountingCustomerParty>${ref?`<cac:BillingReference><cac:InvoiceDocumentReference><cbc:ID>${ref.serie}-${ref.correlativo}</cbc:ID><cbc:DocumentTypeCode>03</cbc:DocumentTypeCode></cac:InvoiceDocumentReference></cac:BillingReference>`:''}<cac:Status><cbc:ConditionCode>1</cbc:ConditionCode></cac:Status>${amount('sac:TotalAmount',d.total)}<sac:BillingPayment>${amount('cbc:PaidAmount',d.valor_venta)}<cbc:InstructionID>01</cbc:InstructionID></sac:BillingPayment>${tax(d.valor_venta,d.igv)}</sac:SummaryDocumentsLine></SummaryDocuments>`;
}
