import test from 'node:test';import assert from 'node:assert/strict';import {XMLParser,XMLValidator} from 'fast-xml-parser';
import {invoiceXml,summaryXml,limaDate} from './ubl.mjs';import {renderInvoice} from '../sunat-pdf/render.mjs';
const cfg={ruc:'20601589410',nombre_empresa:'Empresa de prueba',direccion:'Dirección de prueba'};
const items=[{cantidad:2,precio_unitario:11.8,subtotal:23.6,producto_nombre:'Papel & rollos'}];
const d={tipo:'factura',serie:'F001',correlativo:12,created_at:'2026-10-03T01:00:00Z',cliente_nombre:'Comprador',cliente_documento:'20100070970',descuento:2.36,valor_venta:18,igv:3.24,total:21.24};
const parse=x=>new XMLParser({removeNSPrefix:true,parseTagValue:false,ignoreAttributes:false}).parse(x);
test('Descuento global reduce base e IGV y conserva el valor de las líneas',()=>{const xml=invoiceXml(d,items,cfg,'Alborada 102');assert.equal(XMLValidator.validate(xml),true);const root=parse(xml).Invoice;assert.equal(root.IssueDate,'2026-10-02');assert.equal(root.AllowanceCharge.Amount['#text'],'2.00');assert.equal(root.AllowanceCharge.BaseAmount['#text'],'20.00');assert.equal(root.TaxTotal.TaxSubtotal.TaxableAmount['#text'],'18.00');assert.equal(root.LegalMonetaryTotal.PayableAmount['#text'],'21.24');assert.equal(root.InvoiceLine.Item.Description,'Papel & rollos');});
test('Rechaza montos incoherentes y facturas sin RUC',()=>{assert.throws(()=>invoiceXml({...d,total:30},items,cfg));assert.throws(()=>invoiceXml({...d,cliente_documento:'10725690'},items,cfg));});
test('Boleta y nota de boleta se incluyen en resumen con referencia correcta',()=>{const b={...d,tipo:'boleta',serie:'B001',cliente_documento:'10725690'};let xml=summaryXml(b,cfg,'RC-20261002-1','2026-10-02');assert.equal(XMLValidator.validate(xml),true);assert.equal(parse(xml).SummaryDocuments.SummaryDocumentsLine.DocumentTypeCode,'03');const nc={...b,tipo:'nota_credito',serie:'BC01',motivo_codigo:'01',motivo_descripcion:'Anulación de prueba'};xml=summaryXml(nc,cfg,'RC-20261002-2','2026-10-02',b);assert.equal(parse(xml).SummaryDocuments.SummaryDocumentsLine.BillingReference.InvoiceDocumentReference.ID,'B001-12');assert.equal(XMLValidator.validate(invoiceXml(nc,items,cfg,'Dirección',b)),true);});
test('PDF admite factura, boleta y nota con referencia y direcciones',async()=>{for(const type of ['factura','boleta','nota_credito']){const doc={...d,tipo:type,serie:type==='boleta'?'B001':type==='nota_credito'?'FC01':'F001',motivo_codigo:'01',motivo_descripcion:'Anulación total'};const result=await renderInvoice(invoiceXml(doc,items,cfg,'Alborada 102',type==='nota_credito'?d:null),'PREPARADO_PRODUCCION');assert.ok(result.bytes.length>1000);assert.equal(result.invoice.customerAddress,'Alborada 102');assert.equal(result.invoice.globalDiscount,'2.00');assert.equal(result.invoice.type,type==='boleta'?'03':type==='nota_credito'?'07':'01');}});

test('Redondeo de varias líneas no inventa descuentos',()=>{const small=[{cantidad:1,precio_unitario:1,subtotal:1,producto_nombre:'A'},{cantidad:1,precio_unitario:1,subtotal:1,producto_nombre:'B'}];const xml=invoiceXml({...d,total:2,valor_venta:1.69,igv:.31,descuento:0},small,cfg);const root=parse(xml).Invoice;assert.equal(root.AllowanceCharge,undefined);assert.equal(root.LegalMonetaryTotal.LineExtensionAmount['#text'],'1.69');assert.equal(root.InvoiceLine.map(l=>Number(l.LineExtensionAmount['#text'])).reduce((a,b)=>a+b,0),1.69);});
