import "jsr:@supabase/functions-js@2.5.0/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.57.4";
const j=(x:unknown,s=200)=>Response.json(x,{status:s,headers:{"cache-control":"no-store"}});
Deno.serve(async(req)=>{
 if(req.method!=="POST") return j({ok:false,error:"POST required"},405);
 const body=await req.json().catch(()=>({})); if(!body.guia_id)return j({ok:false,error:"guia_id required"},400);
 const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"); if(!url||!key)return j({ok:false,error:"Backend config missing"},500);
 const sb=createClient(url,key,{auth:{persistSession:false}});
 const {data:g,error}=await sb.from("guias_remision").select("id,serie,correlativo,documento_path,estado_sunat").eq("id",body.guia_id).single();
 if(error||!g)return j({ok:false,error:"GRE not found"},404);
 if(!g.documento_path?.startsWith("gre/signed/"))return j({ok:false,error:"Signed GRE required"},409);
 const {data:f,error:fe}=await sb.storage.from("sunat-private").download(g.documento_path); if(fe||!f)return j({ok:false,error:"Signed XML unavailable"},409);
 const xml=await f.text(); const checks:{name:string,ok:boolean}[]=[];
 const add=(name:string,ok:boolean)=>checks.push({name,ok});
 add("DespatchAdvice UBL 2.1",xml.includes("<cbc:UBLVersionID>2.1</cbc:UBLVersionID>"));
 add("CustomizationID 2.0",xml.includes("<cbc:CustomizationID>2.0</cbc:CustomizationID>"));
 add("Document type 09",/DespatchAdviceTypeCode[^>]*>09<\/cbc:DespatchAdviceTypeCode>/.test(xml));
 add("T-series document ID",new RegExp("<cbc:ID>"+g.serie+"-"+g.correlativo+"<\\/cbc:ID>").test(xml));
 add("Hora local de emisión HH:MM:SS",/<cbc:IssueTime>(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d<\/cbc:IssueTime>/.test(xml));
 add("UBL Signature reference",xml.includes("<cac:Signature>")&&xml.includes("<cbc:URI>#SignatureSP</cbc:URI>"));
 add("XMLDSig present",xml.includes("<ds:Signature")||xml.includes("<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\""));
 add("SHA256 signature",xml.includes("rsa-sha256")&&xml.includes("xmlenc#sha256"));
 add("Issuer party",xml.includes("<cac:DespatchSupplierParty>"));
 add("Recipient party",xml.includes("<cac:DeliveryCustomerParty>"));
 add("Shipment",xml.includes("<cac:Shipment>"));
 add("Origin and destination",xml.includes("<cac:DespatchAddress>")&&xml.includes("<cac:DeliveryAddress>"));
 add("Despatch lines",xml.includes("<cac:DespatchLine>"));
 const failed=checks.filter(x=>!x.ok).map(x=>x.name);
 return j({ok:failed.length===0,validation:"preflight-local",sent_to_sunat:false,checks,failed});
});